Update node.otap.yml

diff --git a/.github/workflows/node.otap.yml b/.github/workflows/node.otap.yml
--- a/.github/workflows/node.otap.yml
+++ b/.github/workflows/node.otap.yml
@@ -29,20 +29,19 @@ jobs:
           git config --global credential.helper store
           echo "https://github.com:${{ secrets.PUBLISH_TOKEN }}" > ~/.git-credentials
           chmod 0600 ~/.git-credentials
-
       - name: Remove dist directory
         run: rm -rf dist
 
       - name: Add generated files
         run: git add .
 
-      - name: Commit changess
+      - name: Commit changes
         run: |
           git commit -m "Clean dist folder"
           git push
         continue-on-error: true
       
-      - name: Fetch branchs information from remote
+      - name: Fetch branch information from remote
         run: git fetch
       
       - name: Show Git status before push
@@ -51,15 +50,16 @@ jobs:
       - name: Merge and push to test branch
         run: |
           git checkout test || git checkout -b test origin/test
-          git merge --no-ff --allow-unrelated-histories -X theirs dev
+          git merge --no-ff --allow-unrelated-histories -X ours dev
           git push origin test
-
       - name: Show Git log after push
         run: git log -1 --oneline
 
   test-to-prod:
     runs-on: ubuntu-latest
     needs: dev-to-test
+    outputs:
+      diff: ${{ steps.compare_versions.outputs.diff }}
 
     steps:
       - name: Checkout code
@@ -78,8 +78,7 @@ jobs:
           git config --global credential.helper store
           echo "https://github.com:${{ secrets.PUBLISH_TOKEN }}" > ~/.git-credentials
           chmod 0600 ~/.git-credentials
-
-      - name: Fetch branchs information from remote
+      - name: Fetch branch information from remote
         run: git fetch
 
       - name: Switch branch dev to test
@@ -97,6 +96,15 @@ jobs:
       - run: npm ci
 
       - run: npm run build:prod
+
+      - name: Compare versions
+        id: compare_versions
+        run: |
+          diff=$(node scripts/compare-release.cjs)
+          echo "Diff result: $diff"
+          echo "diff=$diff" >> $GITHUB_ENV
+          echo "diff=$diff" >> "$GITHUB_OUTPUT"
+        continue-on-error: true
 
       - name: Remove src directory
         run: rm -rf src
@@ -119,21 +127,30 @@ jobs:
           git checkout prod || git checkout -b prod origin/prod
           git merge --no-ff --allow-unrelated-histories -X theirs test
           git push origin prod
-
   prod-publish:
     runs-on: ubuntu-latest
     needs: test-to-prod
+    outputs:
+      diff: ${{ steps.store-version-diff.outputs.diff }}
 
     steps:
       - name: Checkout code
-        uses : actions/checkout@v2
+        uses: actions/checkout@v2
 
       - name: Setup Node.js
-        uses : actions/setup-node@v1
-        with :
-          node-version : 18
-          registry-url : https://npm.pkg.github.com
-          scope : '@lithium-framework'
+        uses: actions/setup-node@v1
+        with:
+          node-version: 18
+          registry-url: https://npm.pkg.github.com
+          scope: '@lithium-framework'
+
+      - name: write output
+        env:
+          DIFF: ${{needs.test-to-prod.outputs.diff}}
+        id: store-version-diff
+        run: |
+          echo "$DIFF"
+          echo "diff=$DIFF" >> "$GITHUB_OUTPUT"
       
       - name: Configure Git with token
         run: |
@@ -146,20 +163,21 @@ jobs:
       - name: Add authentication token to ~/.npmrc
         run: echo "@lithium-framework:registry=https://npm.pkg.github.com/" > .npmrc && echo "//npm.pkg.github.com/:_authToken=${{secrets.PUBLISH_TOKEN}}" >> .npmrc
 
-      - name: Fetch branchs information from remote
+      - name: Fetch branch information from remote
         run: git fetch
 
       - name: Switch branch prod
-        run: git switch -c test origin/prod
+        run: git switch -c prod origin/prod
 
       - name: Publish to GitHub Packages
         run: npm publish || echo "::warning::Publish failed, please check the logs"
 
-      # Steps for building and publishing package for prod branch
-
   main-publish:
     runs-on: ubuntu-latest
     needs: prod-publish
+    permissions:
+      contents: read
+      id-token: write
 
     steps:
       - name: Checkout code
@@ -170,6 +188,9 @@ jobs:
         with:
           node-version: 18.x
           cache: 'npm'
+          registry-url: 'https://registry.npmjs.org/'
+          scope: 'mortallicaxxx'
+          always-auth: true
 
       - name: Configure Git with token
         run: |
@@ -179,38 +200,44 @@ jobs:
             echo "https://github.com:${{ secrets.PUBLISH_TOKEN }}" > ~/.git-credentials
             chmod 0600 ~/.git-credentials
   
-      - name: Fetch branchs information from remote
+      - name: Fetch branch information from remote
         run: git fetch
   
       - name: Switch branch dev to prod
-        run: git switch -c test origin/prod
+        run: git switch -c prod origin/prod
 
       - name: Pull branch from remote
         run: git pull
 
       - name: Compare versions
         id: compare_versions
-        run: node scripts/compare-release.cjs
+        run: echo "diff=${{ needs.prod-publish.outputs.diff }}" # Utilisation de la différence capturée de prod-publish
         continue-on-error: true
 
       - name: Merge to main
         id: merge_prod_to_main
-        if: steps.compare_versions.outputs.diff == 'Not found' || steps.compare_versions.outputs.diff == 'patch' || steps.compare_versions.outputs.diff == 'minor' || steps.compare_versions.outputs.diff == 'major'
+        if: needs.prod-publish.outputs.diff == 'Not found' || needs.prod-publish.outputs.diff == 'patch' || needs.prod-publish.outputs.diff == 'minor' || needs.prod-publish.outputs.diff == 'major'
         run: |
           git checkout main || git checkout -b main origin/main
-          git merge --no-ff --allow-unrelated-histories -X theirs test
+          git merge --no-ff --allow-unrelated-histories -X theirs prod
           git push origin main
 
       - name: Switch branch prod to main
-        if: steps.compare_versions.outputs.diff == 'Not found' || steps.compare_versions.outputs.diff == 'patch' || steps.compare_versions.outputs.diff == 'minor' || steps.compare_versions.outputs.diff == 'major'
-        run: git switch -c prod origin/main
+        if: needs.prod-publish.outputs.diff == 'Not found' || needs.prod-publish.outputs.diff == 'patch' || needs.prod-publish.outputs.diff == 'minor' || needs.prod-publish.outputs.diff == 'major'
+        run: |
+            git fetch
+            git switch main
 
       - name: Pull branch from remote
-        if: steps.compare_versions.outputs.diff == 'Not found' || steps.compare_versions.outputs.diff == 'patch' || steps.compare_versions.outputs.diff == 'minor' || steps.compare_versions.outputs.diff == 'major'
+        if: needs.prod-publish.outputs.diff == 'Not found' || needs.prod-publish.outputs.diff == 'patch' || needs.prod-publish.outputs.diff == 'minor' || needs.prod-publish.outputs.diff == 'major'
         run: git pull
 
-      - name: Publish to npm
-        if: steps.compare_versions.outputs.diff == 'Not found' || steps.compare_versions.outputs.diff == 'patch' || steps.compare_versions.outputs.diff == 'minor' || steps.compare_versions.outputs.diff == 'major'
-        run: npm publish
+      - name: Add authentication token to ~/.npmrc
+        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc
 
-      
+      - name: Publish to npm
+        env:
+            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
+        if: needs.prod-publish.outputs.diff == 'Not found' || needs.prod-publish.outputs.diff == 'patch' || needs.prod-publish.outputs.diff == 'minor' || needs.prod-publish.outputs.diff == 'major'
+        run: npm publish  --provenance --access public || echo "::warning::Publish failed, please check the logs"
+        
